### ISSUE TITLE
double free or corruption on cargo test

### ISSUE THREAD

**Issue by kobigurk** [celo-org/celo-threshold-bls-rs#17]
On one instance of the CI we got:
```
running 30 tests
test curve::zexe::tests::size377 ... ok
test curve::bls12381::tests::basic_group ... ok
test poly::tests::add ... ok
test poly::tests::eval ... ok
test poly::tests::mul ... ok
test poly::tests::new_neg_constant ... ok
test poly::tests::new_poly ... ok
test poly::tests::serialization ... ok
test poly::tests::interpolation ... ok
test sig::tbls::tests::inject ... ok
test poly::tests::full_interpolation ... ok
test tests::share_serialization ... ok
double free or corruption (out)
error: test failed, to rerun pass '--lib'
```

It occurred here: https://app.circleci.com/pipelines/github/celo-org/celo-threshold-bls-rs/60/workflows/66d02c08-1461-49d6-be94-59eb3b61d20f/jobs/151

I'm not able to reproduce it locally, nor on the CI.

**Comment by gakonst** [comment]
Closing as I believe https://github.com/celo-org/celo-threshold-bls-rs/pull/19/commits/746c385201435508ab6dc79fd0036e07e0ebb9c4 fixed it. Will re-open if we see this again.
