### ISSUE TITLE
Security - perform a "group membership" check when partially signing

### ISSUE THREAD

**Issue by kobigurk** [celo-org/celo-threshold-bls-rs#33]
If a malicious user provides a point which is not strictly in the prime order subgroup, they might cause the signer to leak details about their private key. This can be prevent by a "group check", which can be done by multiplying the group order by the blinded message.

**Comment by nikkolasg** [comment]
Just to clarify the issue:
* Do you mean when doing "blind + partial signing" ? 
I believe in the regular partial signing there is no problem since the input is any arbritrary slice of bytes.
* In the case "blind + partial signing", the input is given to the `unmarshal` method: I thought the unmarshalling was doing this group membership; you are saying it is not ?

**Comment by kobigurk** [comment]
* Yeah, only when blinding + partial signing - or more precisely whenever
you don't hash yourself.
* Maybe it does already, you're right! We should verify.

**Comment by gakonst** [comment]
Unmarshalling calls [Zexe's](https://github.com/celo-org/celo-threshold-bls-rs/blob/master/crates/threshold-bls/src/curve/zexe.rs#L102) and [BLS12-381's](https://github.com/celo-org/celo-threshold-bls-rs/blob/master/crates/threshold-bls/src/curve/bls12381.rs#L131-L136) deserialization methods. I agree that the check is probably done there.

What would be an e2e attack vector?

Something like:
1. Attacker generates point
2. Serializes it
3. Sends it to a blind signing method (i.e. one which does not hash)
4. Attack receives the signature and extracts N bits of information about the signer's secret

**Comment by kobigurk** [comment]
Yeah, exactly

**Comment by kobigurk** [comment]
In Zexe, it is checked: https://github.com/scipr-lab/zexe/blob/b01359f595c9a6038c46fe237ca833ea6441a6cc/algebra-core/src/serialize/mod.rs#L356

**Comment by nikkolasg** [comment]
Is there still an issue if the subgroup check is done already ?

**Comment by kobigurk** [comment]
I believe not - do you want to verify in the BLS12-381 implementation before closing?

**Comment by gakonst** [comment]
The check is made [here](https://github.com/filecoin-project/pairing/blob/master/src/bls12_381/ec/g1.rs#L148-L150) I believe. @nikkolasg could you verify that this is the case, so that we can close this?

**Comment by nikkolasg** [comment]
Yes I believe it's done in both curves, so I would close this.

**Comment by kobigurk** [comment]
Sounds good!
